review/urls.py
from django.urls import path
from .views import create,login,logout,homepage,add_service_form
from .views import myservice,admin_login,auth,main
from .views import myservice,admin_login,auth,admin_home, add_category
from .views import service_category, service_question, delete_category

from .views import reject_service,accept_service

urlpatterns = [
    path('',main),
    path('create',create),
    path('login',login),
    path('homepage',homepage),
    path('logout',logout),
    path('add_service_form',add_service_form),
    path('myservice/<int:id>',myservice),
    path('admin_login',admin_login),
    path('auth',auth),
    path('admin_home', admin_home),
    path('admin_service_category', service_category),
    path('add_category', add_category),
    path('delete_category', delete_category),
    path('admin_question', service_question),

    path('accept_service', accept_service),
    path('reject_service', reject_service),
]

reviewpro/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('',include('review.urls'))   
]

review/models.py
from django.db import models

# Create your models here.


class Org(models.Model):
    company = models.CharField(max_length=100)
    password = models.CharField(max_length=100)


class Org_login(models.Model):
    company = models.CharField(max_length=100)
    password = models.CharField(max_length=100)


class Services(models.Model):
    company = models.CharField(max_length=100)
    service = models.CharField(max_length=100)
    category = models.CharField(max_length=100)
    description = models.CharField(max_length=100)
    status = models.CharField(max_length=2, default='P')


class Admin(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    password = models.CharField(max_length=100)

class Admin_login(models.Model):
    username = models.CharField(max_length=100)
    password = models.CharField(max_length=100)

class Category(models.Model):
    name = models.CharField(max_length=200)

class Question(models.Model):
	category_id = models.CharField(max_length=200)
	question = models.TextField(max_length = 500)

review/forms.py
from django import forms
from .models import Org,Services,Admin_login
from .models import Admin
class login_form_org(forms.ModelForm):
	class Meta:
		model = Org
		fields = ('company','password')
	confirm_password = forms.CharField(max_length=100)

class login_form(forms.Form):
	company = forms.CharField(max_length=100)
	password = forms.CharField(max_length=100)

class add_service(forms.ModelForm):
	class Meta:
		model = Services
		fields = ('company','service','category','description')

class admin_login_form(forms.Form):
	class Meta:
		model = Admin
	username = forms.CharField(max_length=10)
	password = forms.CharField(max_length=100)
	email = forms.EmailField(max_length=100)

class auth_form(forms.Form):
	otp_test = forms.CharField(max_length=10)

templates/acceptRejectDiv.html
{% for obj in pending_services %}
<!-- <div class="row"> -->
<p><span style="font-weight: bold">Company : </span>{{obj.company}}</p>
<p><span style="font-weight: bold">Service : </span>{{obj.service}}</p>
<p><span style="font-weight: bold">Category : </span>{{obj.category}}</p>
<p><span style="font-weight: bold">Description : </span>{{obj.description}}</p>

<div class="float-right">
    <button class="btn btn-success" onclick="accepted('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">A</button>
    <button class="btn btn-danger" onclick="rejected('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">R</button>
</div>
<div class="row"></div>
<br>
<hr>
<!-- </div> -->
{% endfor %}

templates/auth.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
  <span>Hey Admin</span>
</nav><br><br>
<div class="container">

<!-- <form method="post" action="/admin_login">
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="submit" value="Submit">
</form> -->
<div class="col-4">
	<div class="alert alert-primary" role="alert">
  Almost there....
</div><br>
 <form action="/auth" method="POST" >
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="submit" value="submit">
</form>
</div>

</div>
</body>

templates/auth_admin.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script>

function accepted(company, service, category) {
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
        }
    };
    xmlhttp.open("GET", "/accept_service?company=" + company + "&service=" + service + "&category=" + category, true);
    xmlhttp.send();
}

function rejected(company, service, category) {
    var xmlhttp = new XMLHttpRequest();
    xmlhttp.onreadystatechange = function() {
        if (this.readyState == 4 && this.status == 200) {
            document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
        }
    };
    xmlhttp.open("GET", "/reject_service?company=" + company + "&service=" + service + "&category=" + category, true);
    xmlhttp.send();
}

</script>
</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
  <span>Hey Admin</span>
</nav><br><br>


<div class="row">
    <div class="col-2"></div>
    <div class="col-6">
        <div class="card" style="width: 30rem;">
            <div class="card-body">
                <h3 class="card-title">Pending Services to verify</h3>
                <p class="card-text"></p>
                <div class="container" id="acceptRejectDiv">
                    {% for obj in pending_services %}
                        <!-- <div class="row"> -->
                            <p><span style="font-weight: bold">Company     : </span>{{obj.company}}</p>
                            <p><span style="font-weight: bold">Service     : </span>{{obj.service}}</p>
                            <p><span style="font-weight: bold">Category    : </span>{{obj.category}}</p>
                            <p><span style="font-weight: bold">Description : </span>{{obj.description}}</p>

                            <div class="float-right">
                                <button class="btn btn-success" onclick="accepted('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">A</button>
                                <button class="btn btn-danger" onclick="rejected('{{ obj.company }}', '{{ obj.service }}', '{{ obj.category }}')">R</button>
                            </div>
                            <div class="row"></div>
                            <br><hr>
                        <!-- </div> -->
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

templates/login.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body>

<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
</nav><br><br>
<div class="container">
	<div class="card">
  <div class="card-header">
    Login
  </div>
  <div class="card-body">
    
  <form action="" method="POST" name='form'>
	{% csrf_token %}
	<input type="text" class="form-control" id="id_password" name="company" placeholder="Enter Company"><br><br>
	<input type="password" class="form-control" id="id_confirm_password" name="password" placeholder="Enter Password"><br><br>
<button type="submit" class="btn btn-primary">Submit</button>	</form>
  </div>
</div>
</div>
</body>

templates/login_admin.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">Review It</span>
  <span>Hey Admin</span>
</nav><br><br>
<div class="container">
<!-- <form method="post" action="/admin_login">
	{% csrf_token %}
	{{ form }}
	<input type="submit" name="submit" value="Submit">
</form> -->
<div class="col-4">
 <form action="/admin_login" method="POST" name='form' class="sm-auto">
	{% csrf_token %}
	<label>Username:</label><br>
	<input type="text" class="form-control" id="id_username" name="username" placeholder="Enter Username">
	<label>Email:</label><br>
	<input type="email" class="form-control" id="id_email" name="email" placeholder="Enter Email">
	<label>Password:</label><br>

	<input type="password" class="form-control" id="id_password" name="password" placeholder="Enter Password"><br>
	<button type="submit" class="btn btn-primary" name="submit">Submit</button>
</form>
</div>
{{ otp }}
{{ error }}
</div>
</body>

templates/login_org.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body><!-- As a link -->

<!-- As a heading -->
<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1 mx-auto">Review It</span>
</nav><br><br>
<center>
<br>	<div class="container">
	<div class="col-6 mr-auto">
		<div class="alert alert-primary" role="alert">
{{ not }}  
</div>

<div class="card">
  <div class="card-header">
   Register
  </div>
    <div class="card-body ">
    <div class="col-12">
    <form action="" method="POST" name='form' class="sm-auto">
	{% csrf_token %}
	<div class="form-group">
	<label>Company:</label><br>
	<input type="text" class="form-control" id="id_company" name="company" placeholder="Enter Company">
</div>
<div class="form-group">
	<label>Password:</label><br>
	<input type="password" class="form-control" id="id_password" name="password" placeholder="Enter Password">
</div>
<div class="form-group">	
	<label>Confirm Password:</label><br>
	<input type="password" class="form-control" id="id_confirm_password" name="confirm_password" placeholder="Enter Password Again"><br><br>
	<button type="submit" class="btn btn-primary">Submit</button>
</form>
</div>
  </div>
</div>
</div>
</center>
</div>
</body>

templates/myservice.html
<head>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head><body>
  <nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">{{ username }}</span>
  <a href="/logout" class="btn btn-primary" role="button" aria-pressed="true">Logout</a>
</nav><br><br>
  <div class="container">
<div class="col-6">
<form action="/add_service_form" style="margin-left: 200px;" method="POST" name='form'>
    {% csrf_token %}
    <label>Company:</label><br>
     <input type="text" class="form-control" id = "id_company" name="company" value="{{ username }}" placeholder="Company">
    <label>Service:</label><br>
    <input type="text" class="form-control" id = "id_service" placeholder="Name of the service" value="{{ object.service }}" name="service">
    <label>Category:</label><br>
    <input type="text" class="form-control" placeholder="Category" id = "id_category"  value="{{ object.category }}"name="category">
    <label>Description:</label><br>
    <input type="text" class="form-control" name="description" id="id_description" value="{{ object.description }}"placeholder="Description">
    <br>
  <button type="submit" class="btn btn-primary" name="sub">Submit</button> 
</form>
</div>
</div>
</body>

templates/service_category_home.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script>

        function accepted(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/accept_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

        function rejected(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/reject_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

    </script>
</head>

<body>

    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Review It</span>
        <span>Hey Admin</span>
    </nav><br><br>

    <div class="row">
        <div class="col-1"></div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Add new service Category</h3>
                    <p class="card-text"></p>
                    <br>
                    <form action="/add_category" method="post">
                        {% csrf_token %}
                        <input type="text" class="form-control" placeholder="Enter Service Category" name="service_category">
                        <div class="row"></div>
                        <br>
                        <input type="submit" name="submit" class="btn btn-success" value="Add">
                    </form>
                </div>
            </div>
        </div>

        <div class="col-2"></div>
        <div class="col-4">
            <div class="card">
                <div class="card-body">
                    <h3 class="card-title">Service Category</h3>
                    <p class="card-text"></p>
                    <br>
                    {% for category in categories %}
                    <form action="/delete_category" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="service_category" value="{{ category.id }}">
                        <div class="container">
                            <span>{{ category.name }}</span>
                            <button class="btn btn-danger float-right">Delete</button>
                        </div>
                        <br>
                        <hr>
                    </form>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>

</body>

templates/service_question_home.html
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS"
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k"
        crossorigin="anonymous"></script>
    <script>

        function accepted(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/accept_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

        function rejected(company, service, category) {
            var xmlhttp = new XMLHttpRequest();
            xmlhttp.onreadystatechange = function () {
                if (this.readyState == 4 && this.status == 200) {
                    document.getElementById("acceptRejectDiv").innerHTML = this.responseText;
                }
            };
            xmlhttp.open("GET", "/reject_service?company=" + company + "&service=" + service + "&category=" + category, true);
            xmlhttp.send();
        }

    </script>
</head>

<body>

    <nav class="navbar navbar-light bg-light">
        <span class="navbar-brand mb-0 h1">Review It</span>
        <span>Hey Admin</span>
    </nav><br><br>

</body>

templates/test.html
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

</head>
<body>
	<nav class="navbar navbar-light bg-light">
  <span class="navbar-brand mb-0 h1">{{ username }}</span>
  <a href="/logout" class="btn btn-primary" role="button" aria-pressed="true">Logout</a>
</nav><br><br>
	<div class="container">
	
{% if error == "" %}
<a href="/login">Please Login</a>
{% else %}
<center><h2>Welcome Aboard</h2></center><br><br>
<div class="row">
	<div class="col-4">
		<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title">Browse My Services.</h5>
    <p class="card-text"></p>
    {% for obj in objects %}
        <a href="/myservice/{{ obj.id }}">{{ obj.service }}</a><br>
        {% endfor %}
      </div>
</div>
	</div>
	<div class="col-2">
		
	</div>
	<div class="col-6">
	<div class="card" style="width: 30rem;">
  <div class="card-body">
    <h5 class="card-title">Add a Service</h5>
    <p class="card-text"></p>
  <form action="/add_service_form" method="POST" name='form'>
  	{% csrf_token %}
  	<!-- <label>Company:</label><br> -->
    <input type="text" class="form-control" id = "id_company" name="company" value="{{ username }}" placeholder="Company" hidden>
     <label>Service:</label><br>
    <input type="text" class="form-control" id = "id_service" placeholder="Name of the service" name="service">
    <label>Category:</label><br>
    <input type="text" class="form-control" placeholder="Category" id = "id_category" name="category">
    <label>Description:</label><br>
    <input type="text" class="form-control" name="description" id="id_description" placeholder="Description">
    <br>
  <button type="submit" class="btn btn-primary" name="sub">Submit</button> 
</form>
       
  </div>
</div>
	</div>
</div>
{% endif %}
</div>
</body>